### ISSUE TITLE
implement SSL for autobahn

### ISSUE THREAD

**Issue by tlwt** [tlwt/Productive4SwedenDemo#2]
Reverse proxy (traefik)?

**Comment by lgrkvst** [comment]
Oh. Does this mean we're going `wss://`?

**Comment by NoahWinneberger** [comment]
Nope, https :)

On 22. Mar 2019, at 11:17, Christian Lagerkvist <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh. Does this mean we're going wss://?
